/**
 * Copyright (c) 2021, Zoe J. Bare
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#ifndef _XENON_BUILT_IN_ID_H_
#define _XENON_BUILT_IN_ID_H_

/*---------------------------------------------------------------------------------------------------------------------*/

enum XenonBuiltInId
{
	XENON_BUILT_IN_OP_ADD_BOOL,
	XENON_BUILT_IN_OP_ADD_INT8,
	XENON_BUILT_IN_OP_ADD_INT16,
	XENON_BUILT_IN_OP_ADD_INT32,
	XENON_BUILT_IN_OP_ADD_INT64,
	XENON_BUILT_IN_OP_ADD_UINT8,
	XENON_BUILT_IN_OP_ADD_UINT16,
	XENON_BUILT_IN_OP_ADD_UINT32,
	XENON_BUILT_IN_OP_ADD_UINT64,
	XENON_BUILT_IN_OP_ADD_FLOAT32,
	XENON_BUILT_IN_OP_ADD_FLOAT64,
	XENON_BUILT_IN_OP_ADD_STRING,

	XENON_BUILT_IN_OP_SUB_BOOL,
	XENON_BUILT_IN_OP_SUB_INT8,
	XENON_BUILT_IN_OP_SUB_INT16,
	XENON_BUILT_IN_OP_SUB_INT32,
	XENON_BUILT_IN_OP_SUB_INT64,
	XENON_BUILT_IN_OP_SUB_UINT8,
	XENON_BUILT_IN_OP_SUB_UINT16,
	XENON_BUILT_IN_OP_SUB_UINT32,
	XENON_BUILT_IN_OP_SUB_UINT64,
	XENON_BUILT_IN_OP_SUB_FLOAT32,
	XENON_BUILT_IN_OP_SUB_FLOAT64,

	XENON_BUILT_IN_OP_MUL_BOOL,
	XENON_BUILT_IN_OP_MUL_INT8,
	XENON_BUILT_IN_OP_MUL_INT16,
	XENON_BUILT_IN_OP_MUL_INT32,
	XENON_BUILT_IN_OP_MUL_INT64,
	XENON_BUILT_IN_OP_MUL_UINT8,
	XENON_BUILT_IN_OP_MUL_UINT16,
	XENON_BUILT_IN_OP_MUL_UINT32,
	XENON_BUILT_IN_OP_MUL_UINT64,
	XENON_BUILT_IN_OP_MUL_FLOAT32,
	XENON_BUILT_IN_OP_MUL_FLOAT64,

	XENON_BUILT_IN_OP_DIV_BOOL,
	XENON_BUILT_IN_OP_DIV_INT8,
	XENON_BUILT_IN_OP_DIV_INT16,
	XENON_BUILT_IN_OP_DIV_INT32,
	XENON_BUILT_IN_OP_DIV_INT64,
	XENON_BUILT_IN_OP_DIV_UINT8,
	XENON_BUILT_IN_OP_DIV_UINT16,
	XENON_BUILT_IN_OP_DIV_UINT32,
	XENON_BUILT_IN_OP_DIV_UINT64,
	XENON_BUILT_IN_OP_DIV_FLOAT32,
	XENON_BUILT_IN_OP_DIV_FLOAT64,
};

/*---------------------------------------------------------------------------------------------------------------------*/

#endif /* _XENON_BUILT_IN_ID_H_ */
