/* Copyright (C) 2023, Zoe J. Bare */
/* DO NOT EDIT, changes will be lost! This file was automatically generated by generate-utf32-table.py. */

#include "../../HqBuildEnv.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HQ_UTF32_FULL_MAPPING_ARRAY_LENGTH 3
#define HQ_UTF32_RECORD_ENTRY_COUNT        4332
#define HQ_UTF32_RECORD_INDEX_COUNT        125252
#define HQ_UTF32_RECORD_INDEX_TYPE         uint16_t

struct HqUtf32Mapping
{
	char32_t full[HQ_UTF32_FULL_MAPPING_ARRAY_LENGTH];
	char32_t simple;
	size_t fullLength;
};

struct HqUtf32Record
{
	struct HqUtf32Mapping lowerCase;
	struct HqUtf32Mapping upperCase;
	struct HqUtf32Mapping titleCase;
	char32_t codePoint;
};

struct HqUtf32RecordTable
{
	struct HqUtf32Record records[HQ_UTF32_RECORD_ENTRY_COUNT];
	HQ_UTF32_RECORD_INDEX_TYPE indices[HQ_UTF32_RECORD_INDEX_COUNT];
};

HQ_BASE_API extern const struct HqUtf32RecordTable utf32RecordTable;

#ifdef __cplusplus
}
#endif
